name: Deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Clone chart repository
        uses: actions/checkout@v2
        with:
          repository: daviddoichita/laracoin-chart

      - name: Check status
        run: ls
      
