name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure .env
        run: |
          cp .env.example .env
          sed -i 's/^DB_DATABASE=.*/DB_DATABASE=${{ vars.DB_DATABASE }}/'
          cat .env
