name: Deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repo
        uses: actions/checkout@v2

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - 
        name: Clone chart repository
        uses: actions/checkout@v2
        with:
          repository: daviddoichita/laracoin-chart
      -
        name: Bump app version
        run: |
           sed -Ei 's/appVersion: "([0-9]+)\.([0-9]+)\.([0-9]+)"/echo appVersion: \"\1.\2.$((\3 + 1))\"/e' chart/Chart.yaml
      -
        name: Push changes
        run: |
          git config user.name "laracoin-workflow"
          git config user.email "daviddoichita@proton.me"
          git remote set-url origin https://x-access-token:${{ secrets.LARACOIN_CHART_PAT }}@github.com/daviddoichita/laracoin-chart.git
          git add .
          git commit -m 'Bump app version'
          git push origin main
      
