name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    # needs: build
    permissions:
      contents: write
    steps:
      - 
        name: Clone chart repository
        uses: actions/checkout@v2
        with:
          repository: daviddoichita/laracoin-chart
          token: ${{ secrets.LARACOIN_CHART_PAT }}
      -
        name: Bump app version
        run: |
           sed -Ei 's/appVersion: "([0-9]+)\.([0-9]+)\.([0-9]+)"/echo appVersion: \"\1.\2.$((\3 + 1))\"/e' chart/Chart.yaml
      - 
        name: Push changes
        run: |
          git add .
          git commit -m 'Bump app version'
          git push
      
