name: Run SonarCloud Scanning

#on: 
#  push:
#    branches:
#      - prod

on: workflow_dispatch

jobs:
  scan:
    runs-on: microk8s
    steps:
      - name: Checkout repo
        id: checkout_repo
        uses: actions/checkout@v2
      - name: Configure networking
        run: |
          echo "${{ secrets.SERVER_URL }} microk8s.local" >> sudo tee /etc/hosts
      - name: Run scanning
        id: run_scanning
        uses: SonarSource/sonarqube-scan-action@v5.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_LOCAL }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
