name: Run SonarCloud Scanning

on: 
  push:
    branches:
      - prod

jobs:
  scan:
    runs-on: microk8s
    steps:
      - name: Checkout repo
        id: checkout_repo
        uses: actions/checkout@v2
      - name: Run scanning
        id: run_scanning
        uses: SonarSource/sonarqube-scan-action@v5.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
