name: Test runner

on: workflow_dispatch

jobs:
  prepare_job:
    runs-on: ddoichita
    container:
      image: node:latest
    steps:
      - name: Test node
        run: |
          node -v
          npm -v

  test:
    runs-on: ddoichita
    steps:
      - name: Display message
        id: display_message
        run: | 
          echo 'ls'
          echo 'message=ok' >> $GITHUB_OUTPUT
      - name: Test runner image
        id: test-runner-image
        run: |
          cat /etc/*-release
      - name: Test outputs and step summary
        if: always()
        run: |
          echo "## Test step summary" >> $GITHUB_STEP_SUMMARY

          if [ "${{ steps.display_message.outputs.message }}" != "ok" ]; then
            echo "- **Estado**: ❌ Fallido" >> $GITHUB_STEP_SUMMARY
          else
            echo "- **Estado**: ✅ OK" >> $GITHUB_STEP_SUMMARY
          fi
